### ISSUE TITLE
After running htpdate, the time becomes 2003, it should be 2023, running on Windows 10 22H2

### ISSUE THREAD

**Issue by LostMyMind** [bobwen-dev/htpdate#2]
I am using google translate because i am not proficient in english.
Now it is March 3, 2023. After I use htpdate, the system time becomes March 1, 2003. I don't know why.
I checked other htpdate libraries on github and found that this is also the case. I don't know if it can be used as a reference.
![image](https://user-images.githubusercontent.com/57167544/222708822-82043316-1953-4c5d-a0d8-289328cbf522.png)
![image](https://user-images.githubusercontent.com/57167544/222708846-2d9d33fd-65ad-494d-b7e4-2ed6f3fb602f.png)
(Sorry, was just misled by other questions, month and day are not swapped)

**Comment by LostMyMind** [comment]
Sorry, Google translation is not very reliable, "the system time becomes March 1, 2003" here should be "the system time becomes **March 3, 2003**"

**Comment by bobwen-dev** [comment]
This is a parsing failure caused by the Windows date format, which can be prevented with command like this:
`htpdate -s -C "[time ]HH:mm:ss.SS[ && date ]YY-MM-DD" www.baidu.com`

The date format in Windows is `MM-DD-YY`, while in Chinese version it is `YYYY-MM-DD`
